# Generated by Django 6.0 on 2025-12-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_age_alter_customer_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
    ]
