# Generated by Django 6.0 on 2025-12-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Elektrik', 'Elektrik'), ('Hibrit', 'Hibrit')], default='Benzin', max_length=20, verbose_name='Yakıt Tipi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='luggage',
            field=models.IntegerField(default=3, verbose_name='Bavul Kapasitesi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(default=5, verbose_name='Koltuk Sayısı'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Otomatik', 'Otomatik'), ('Manuel', 'Manuel')], default='Otomatik', max_length=20, verbose_name='Vites'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
