# Generated by Django 6.0 on 2025-12-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_fuel_type_alter_vehicle_luggage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='branch',
            field=models.CharField(choices=[('City Center', 'City Center'), ('Airport', 'Airport'), ('Bus Station', 'Bus Station')], default='City Center', max_length=50),
        ),
    ]
